version: '3'
services:
  chat_web_database:
    image: mongodb/mongodb-community-server:latest
    container_name: chat_web_database_container
    ports:
      - "7017:27017"
    volumes:
      - /database/mongod.conf:/etc/mongod.conf
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
  chat_web_backend:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: chat_web_backend_container
    depends_on:
      - chat_web_database
    restart: unless-stopped
    volumes:
      - ./backend:/app
    environment:
      - HOST_NAME=${HOST_NAME}
  chat_web_frontend:
    build: ./frontend
    ports:
      - "8080:80"
    container_name: chat_web_frontend_container
    volumes:
      - ./frontend:/usr/share/nginx/html
    environment:
      - HOST_NAME=${HOST_NAME}
volumes:
  mongo-data:
