name: Initialize MongoDB Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  initialize-mongodb:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start MongoDB Docker container
      run: docker run --name mongodb -p 27017:27017 -d mongodb/mongodb-community-server:latest

    - name: Wait for MongoDB to initialize
      run: sleep 15s

    - name: Init database
      run: |
        cd backend
        npm install
        node init_database.js

  generate-config:
    runs-on: ubuntu-latest
    needs: initialize-mongodb
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate JSON Config
        run: |
          cd backend
          echo '{"url": "mongodb://127.0.0.1:27017"}' > config.json

      - name: Upload config.json
        uses: actions/upload-artifact@v2
        with:
          name: config
          path: backend/config.json

  init-server:
    name: Initialize Server
    runs-on: ubuntu-latest
    needs: generate-config

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download config.json
        uses: actions/download-artifact@v2
        with:
          name: config
          path: backend

      - name: Start server
        run: |
          cd backend
          npm install
          node server.js

  test-responses:
    name: Test Responses
    needs: init-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          cd backend
          npm install --save-dev jest
          npm test
